baseurl: "http://shadowfax-chc.github.io/recipes"
languageCode: "en-us"
title: "Recipes"
theme: "fax"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
canonifyurls: true
params:
  navigation:
    brand: Recipes
  menu:
    items:
      -
        url: /entrees/
        name: Entrees
